name: Build ImageBuilder
# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  schedule:
    # https://crontab.guru
    # Cache 切れ回避
    - cron: "0 02 * * 1,4" # daily 11:00 +0900 月,木

  push:
    paths:
      - .github/workflows/build-imagebuilder.yml

  pull_request:
    types:
      - opened
      - synchronize
      - closed

  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "v23.05.2"
        description: OpenWrt version
        type: string

      make_options:
        required: true
        default: "V=c"
        description: |
          make options. (default: "V=c")

          [s]: stdout+stderr, [c]: commands, [w]: warnings/errors only
        type: choice
        options:
          - "V=c"
          - "V=w"
          - "V=sc"
          - "V=sw"

jobs:
  ImageBuilder:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # default 6 hour
    env:
      TZ: Asia/Tokyo
      COMMIT_SHORT_SHA: null
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4.1.1

      - name: Set short git commit SHA
        id: vars
        run: |+
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - uses: actions/github-script@v7.0.1
        id: LastKernelBuild
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |+
            const listWorkflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-kernel.yml',
              branch: 'main',
              status: 'success',
              per_page: 1,
            });

            return listWorkflowRuns.data.workflow_runs[0]

      - name: "Check outputs"
        run: |+
          echo ${{ toJson(steps.LastKernelBuild.outputs.result) }}

      - name: Download buildimage artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.LastKernelBuild.outputs.result.id }}
          pattern: openwrt-imagebuilder-*
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      # - name: Installing dependencies
      #   run: |+
      #     sudo apt update
      #     sudo apt install build-essential --no-install-recommends --no-install-suggests --yes \
      #     clang flex bison g++ gawk gcc-multilib g++-multilib gettext git \
      #     libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
