name: Build ImageBuilder
# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  schedule:
    # https://crontab.guru
    # Cache 切れ回避
    - cron: "0 06 * * 1,4" # daily 14:00 +0900 月,木

  workflow_call: {}
  workflow_dispatch: {}

jobs:
  ImageBuilder:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # default 6 hour
    env:
      TZ: Asia/Tokyo
      COMMIT_SHORT_SHA: null
      BUILD_OPENWRT_VERSION: null
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4.1.1

      - name: Set short git commit SHA
        id: vars
        run: |+
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Get last kernel-build runs
        uses: actions/github-script@v7.0.1
        id: LastKernelBuild
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |+
            const listWorkflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-kernel.yml',
              branch: 'main',
              status: 'success',
              per_page: 1,
            });

            return listWorkflowRuns.data.workflow_runs[0]

      - name: "Check outputs"
        run: |+
          set -eux

          echo ${{ toJson(steps.LastKernelBuild.outputs.result) }}

      - name: Download buildimage artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ fromJson(steps.LastKernelBuild.outputs.result).id }}
          pattern: openwrt-imagebuilder-*
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true

      - name: Display structure of downloaded files
        run: |+
          set -eux

          ls -R

      - name: Installing dependencies
        run: |+
          set -eux

          sudo apt update
          sudo apt install --no-install-recommends --no-install-suggests --yes \
          build-essential libncurses-dev zlib1g-dev gawk \
          gettext libssl-dev xsltproc rsync wget  unzip python3 python3-distutils

      - name: Unpack the archive
        run: |+
          set -eux

          mkdir -p imagebuilder
          tar -Jxf openwrt-imagebuilder-*.tar.xz --strip-components 1 -C ./imagebuilder

          cp -av ./packages ./imagebuilder/packages

      - name: Set OpenWrt version
        run: |+
          set -eux
          echo "BUILD_OPENWRT_VERSION=$(cat ./version.tag) ($(cat ./version.buildinfo))" >> $GITHUB_ENV
          echo "BUILD_OPENWRT_TAG=$(cat ./version.tag)" >> $GITHUB_ENV

      - name: Building image
        working-directory: imagebuilder
        run: |+
          set -eux

          make image \
            PROFILE="fortinet_fg-50e" \
            DISABLED_SERVICES="$(grep -v -E '^(#|$)' ${{ github.workspace }}/config/imagebuilder/disable_services.txt | tr '\n' ' ')" \
            PACKAGES="$(grep -v -E '^(#|$)' ${{ github.workspace }}/config/imagebuilder/packages_list.txt | tr '\n' ' ')" \
            FILES="${{ github.workspace }}/config/imagebuilder/files"

          ls -lah ./bin/targets/mvebu/cortexa9

          mv -v ./bin/targets/mvebu/cortexa9/openwrt-${BUILD_OPENWRT_TAG#v}-mvebu-cortexa9-fortinet_fg-50e-squashfs-sysupgrade.bin \
            ./bin/targets/mvebu/cortexa9/openwrt-${BUILD_OPENWRT_TAG#v}-${COMMIT_SHORT_SHA}-mvebu-cortexa9-fortinet_fg-50e-squashfs-sysupgrade.bin

      - name: Generate Release note
        working-directory: imagebuilder
        run: |+
          set -eux

          cat <<EOF> ${{ github.workspace }}-ReleaseNote.txt
          * OpenWrt ${{ env.BUILD_OPENWRT_VERSION }}
          * My repo Commit hash: ${{ github.sha }}

          This firmware was built by @naa0yama

          ## sha256sums

          \`\`\`bash
          $( cat ./bin/targets/mvebu/cortexa9/sha256sums | grep -v -e '\*packages\/' )

          \`\`\`

          ## config

          \`\`\`bash
          # DISABLED_SERVICES
          $( cat ../config/imagebuilder/disable_services.txt )

          # PACKAGES
          $( cat ../config/imagebuilder/packages_list.txt )

          # FILES
          $( grep -r -E '*' ../config/imagebuilder/files | sed -e 's@\.\./config/imagebuilder/files@@g' )

          \`\`\`


          ## Packages

          <details>
            <summary>Packages files</summary>

          \`\`\`bash
          $( cat ./imagebuilder/packages )

          \`\`\`

          </details>

          EOF

      - name: Cleanup pre-releases
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |+
            const __prereleases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });
            const prereleases = __prereleases.data

            for (const index in prereleases) {
              if (prereleases[index].draft == true &&
                  prereleases[index].prerelease == true ) {
                console.log('delte pre-release ' + prereleases[index]['id'] + '\t' + prereleases[index]['name'])

                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: prereleases[index]['id'],
                });
              }
            }

            console.log('end run')

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          name: OpenWrt Custom ${{ env.BUILD_OPENWRT_VERSION }}-${{ env.COMMIT_SHORT_SHA }}
          tag_name: ${{ env.BUILD_OPENWRT_VERSION }}-${{ env.COMMIT_SHORT_SHA }}
          body_path: ${{ github.workspace }}-ReleaseNote.txt
          draft: true
          prerelease: true
          files: |
            ./openwrt-*mvebu-cortexa9-fortinet_fg-50e-initramfs-kernel.bin
            ./imagebuilder/bin/targets/mvebu/cortexa9/openwrt-*mvebu-cortexa9-fortinet_fg-50e-squashfs-sysupgrade.bin
