name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "23.05.2"
        description: OpenWrt version
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # default 6 hour
    env:
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Installing dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget

      - name: git clone openwrt/openwrt
        run: |
          set -eux

          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git pull

      - name: configure code version
        working-directory: openwrt
        run: |
          set -eux

          git branch -a
          git tag
          git checkout v${{ inputs.version }}

      - name: Cache dependencies
        id: cache-build
        uses: actions/cache@v3.3.3
        with:
          path: |
            ./openwrt/bin/
            ./openwrt/build_dir/
            ./openwrt/dl/
            ./openwrt/feeds/
            ./openwrt/staging_dir/
          key: built-${{ inputs.version }}

      - name: Cache hit check
        run: |
          echo "-->${{steps.cache-build.outputs.cache-hit}}<--"

      - name: Update the feeds
        working-directory: openwrt
        run: |
          set -eux

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Expand to full config
        working-directory: openwrt
        run: |
          set -eux

          cp ../mvebu-cortexa9-fortinet_fg-50e.ini .config
          make defconfig

      - name: Building firmware
        working-directory: openwrt
        run: |
          set -eux

          time make -j $(($(nproc)+1)) V=sc

      - name: Archive artifacts
        working-directory: openwrt/bin/targets/mvebu/cortexa9
        run: |
          set -eux

          tar -zcvf openwrt-${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}-mvebu-cortexa9-fortinet_fg-50e.tar.gz ./*

      - uses: actions/create-release@master
        id: create_release # ファイルアップロードに outputs の値を使用するため ID が必要
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}
          release_name: OpenWrt Custom ${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}
          body: |
            * OpenWrt ${{ inputs.version }}
            * My repo Commit hash: `${{ env.COMMIT_SHORT_SHA }}`

            This firmware was built by @naa0yama
          draft: true
          prerelease: true

      - uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # リリースのアップロード URL (必須)
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # 添付ファイルのパス (必須)
          asset_path: openwrt/bin/targets/mvebu/cortexa9/openwrt-${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}-mvebu-cortexa9-fortinet_fg-50e.tar.gz
          # 添付ファイルの表示名 (必須)
          asset_name: openwrt-${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}-mvebu-cortexa9-fortinet_fg-50e.tar.gz
          # 添付ファイルに対応する content-type (必須)
          asset_content_type: application/x-gzip
