name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "v23.05.2"
        description: OpenWrt version
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/naa0yama/openwrt-fortigate-50e-custom-image/build-system:${{ inputs.version }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    timeout-minutes: 360 # default 6 hour
    env:
      TZ: Asia/Tokyo
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Expand to full config
        # working-directory: openwrt
        run: |
          set -eux

          cp ../mvebu-cortexa9-fortinet_fg-50e.ini .config
          make defconfig

      - name: Building firmware
        # working-directory: openwrt
        run: |
          set -eux

          cd .
          time make --directory ./ -j $(($(nproc)+1)) download world

      - name: Archive artifacts
        working-directory: bin/targets/mvebu/cortexa9
        run: |
          set -eux

          tar -zcvf openwrt-${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}-mvebu-cortexa9-fortinet_fg-50e.tar.gz ./*

      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          name: OpenWrt Custom ${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}
          tag_name: ${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}
          body: |
            * OpenWrt ${{ inputs.version }}
            * My repo Commit hash: `${{ env.COMMIT_SHORT_SHA }}`

            This firmware was built by @naa0yama

          draft: true
          prerelease: true
          files: |
            bin/targets/mvebu/cortexa9/openwrt-${{ inputs.version }}-${{ env.COMMIT_SHORT_SHA }}-mvebu-cortexa9-fortinet_fg-50e.tar.gz
