name: Build system provisioning
# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  # push:
  #   paths:
  #     - .github/workflows/build-system.yml
  #     - Dockerfile
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #     - closed
  workflow_dispatch:
    inputs:
      make_options:
        required: true
        default: "V=c"
        description: |
          make options. (default: "V=c")

          [s]: stdout+stderr, [c]: commands, [w]: warnings/errors only
        type: choice
        options:
        - "V=c"
        - "V=w"
        - "V=sc"
        - "V=sw"

jobs:
  create-build-system:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        platform:
          - "fortinet_fg-50e"
    timeout-minutes: 180 # default 6 hour
    env:
      TZ: Asia/Tokyo
      OPENWRT_VERSION: null
    permissions:
      packages: write

    steps:
      - name: "get build environment"
        run: |
          set -eux

          bash --version
          bzip2 --version
          git --version
          gcc --version
          gawk --version
          gzip --version
          make --version
          openssl version
          patch --version
          perl --version
          python3 --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: "get openwrt version from Dockerfile"
        run: |
          set -eux

          OPENWRT_VERSION=$(grep -oP '(?<=OPENWRT_VERSION=").+(?=")' Dockerfile)
          if [ -z "$OPENWRT_VERSION" ]; then
            exit 1
          fi

          echo "OPENWRT_VERSION=${OPENWRT_VERSION}" >> $GITHUB_ENV

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/build-system
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

            # OpenWrt version tag
            type=raw,value=${{ env.OPENWRT_VERSION }},enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        env:
          BUILD_MAKE_OPTIONS: ${{ inputs.make_options }}
        with:
          push: true
          cache-from: type=gha,scope=build-system-${{ env.OPENWRT_VERSION }}
          cache-to: type=gha,mode=max,scope=build-system-${{ env.OPENWRT_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  notification:
    runs-on: ubuntu-latest
    needs:
      - create-build-system
    timeout-minutes: 5 # default 6 hour
    env:
      TZ: Asia/Tokyo
    permissions:
      pull-requests: write

    steps:
      - uses: actions/github-script@v7.0.1
        if: github.event.pull_request.merged != true && always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            Notifications @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
