name: Build ImageBuilder
# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  schedule:
    # https://crontab.guru
    # Cache 切れ回避
    - cron: "0 02 * * 1,4" # daily 11:00 +0900 月,木

  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
    branches:
      - 'main'
    paths:
      - .github/workflows/build-imagebuilder.yml
      - config/imagebuilder/disable_services.txt
      - config/imagebuilder/files.txt
      - config/imagebuilder/packages_list.txt

  workflow_dispatch:

jobs:
  ImageBuilder:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # default 6 hour
    env:
      TZ: Asia/Tokyo
      COMMIT_SHORT_SHA: null
      BUILD_OPENWRT_VERSION: null
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v4.1.1

      - name: Set short git commit SHA
        id: vars
        run: |+
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - uses: actions/github-script@v7.0.1
        id: LastKernelBuild
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |+
            const listWorkflowRuns = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-kernel.yml',
              branch: 'main',
              status: 'success',
              per_page: 1,
            });

            return listWorkflowRuns.data.workflow_runs[0]

      - name: "Check outputs"
        run: |+
          set -eux

          echo ${{ toJson(steps.LastKernelBuild.outputs.result) }}

      - name: Download buildimage artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ fromJson(steps.LastKernelBuild.outputs.result).id }}
          pattern: openwrt-imagebuilder-*
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true

      - name: Display structure of downloaded files
        run: |+
          set -eux

          ls -R

      - name: Installing dependencies
        run: |+
          set -eux

          sudo apt update
          sudo apt install --no-install-recommends --no-install-suggests --yes \
          build-essential libncurses-dev zlib1g-dev gawk \
          gettext libssl-dev xsltproc rsync wget  unzip python3 python3-distutils

      - name: Unpack the archive
        run: |+
          set -eux

          mkdir -p imagebuilder
          tar -Jxf openwrt-imagebuilder-*.tar.xz --strip-components 1 -C ./imagebuilder

          cp -av ./packages ./imagebuilder/packages

      - name: set OpenWrt version
        run: |+
          set -eux
          echo "BUILD_OPENWRT_VERSION=$(cat ./version.tag) ($(cat ./version.buildinfo))" >> $GITHUB_ENV

      - name: Building image
        working-directory: imagebuilder
        run: |+
          set -eux

          make image \
            PROFILE="fortinet_fg-50e" \
            DISABLED_SERVICES="$(grep -v -E '^(#|$)' ../config/imagebuilder/disable_services.txt | tr '\n' ' ')" \
            PACKAGES="$(grep -v -E '^(#|$)' ../config/imagebuilder/packages_list.txt | tr '\n' ' ')" \
            FILES=\"../config/imagebuilder/files.txt\"

          ls -lah ./bin/targets/mvebu/cortexa9

      - name: Generate Release note
        working-directory: imagebuilder
        run: |+
          set -eux

          cat <<EOF> ${{ github.workspace }}-ReleaseNote.txt
          * OpenWrt ${{ env.BUILD_OPENWRT_VERSION }}
          * My repo Commit hash: \`${{ env.COMMIT_SHORT_SHA }}\`

          This firmware was built by @naa0yama

          ## sha256sums

          \`\`\`bash
          $( cat ./bin/targets/mvebu/cortexa9/sha256sums | grep -v -e '\*packages\/' )

          \`\`\`

          ## config

          \`\`\`bash
          # DISABLED_SERVICES
          $( cat ../config/imagebuilder/disable_services.txt )

          # PACKAGES
          $( cat ../config/imagebuilder/packages_list.txt )

          # FILES
          $( cat ../config/imagebuilder/files.txt )

          \`\`\`

          EOF

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          name: OpenWrt Custom ${{ env.BUILD_OPENWRT_VERSION }}-${{ env.COMMIT_SHORT_SHA }}
          tag_name: ${{ env.BUILD_OPENWRT_VERSION }}-${{ env.COMMIT_SHORT_SHA }}
          body_path: ${{ github.workspace }}-ReleaseNote.txt
          draft: true
          prerelease: true
          files: |
            ./openwrt-*mvebu-cortexa9-fortinet_fg-50e-initramfs-kernel.bin
            ./imagebuilder/bin/targets/mvebu/cortexa9/openwrt-*mvebu-cortexa9-fortinet_fg-50e-squashfs-sysupgrade.bin
